RedHatCloudForms/cfme-cloud_services

lib/cfme/cloud_services/data_collector.rb
Collect the provider record GUID to be used for the main [`source.uid`](https://github.com/ManageIQ/topological_inventory-ingress_api/blob/master/public/doc/openapi-3-v0.0.2.json#L1255-L1257) which will be created on first upload.
```
"ManageIQ::Providers::Vmware::InfraManager": {
"id": 1,
"api_version": "6.7.1",
"guid": "4a231bbe-1861-408e-ac05-1a2a5e06c29a",
"name": "dev-vc67",
"type": "ManageIQ::Providers::Vmware::InfraManager",
}
```
=> Add GUID to provider for source uid

lib/cfme/cloud_services/data_collector.rb
Collect CPUs and RAM size for VMs and Hosts for [vm.cpus](https://github.com/ManageIQ/topological_inventory-ingress_api/blob/master/public/doc/openapi-3-v0.0.2.json#L2849-L2852), [vm.memory](https://github.com/ManageIQ/topological_inventory-ingress_api/blob/master/public/doc/openapi-3-v0.0.2.json#L2892-L2895), [host.cpus](https://github.com/ManageIQ/topological_inventory-ingress_api/blob/master/public/doc/openapi-3-v0.0.2.json#L1137-L1140), and [host.memory](https://github.com/ManageIQ/topological_inventory-ingress_api/blob/master/public/doc/openapi-3-v0.0.2.json#L1153-L1156) on the topology size.
```
"vms": [
{
"id": 43,
"name": "billy_5_10_4_2",
"type": "ManageIQ::Providers::Vmware::InfraManager::Vm",
"ems_ref": "vm-301",
"ram_size": 12288,
"cpu_total_cores": 4
}
```
```
"hosts": [
{ …
```
=> Collect CPU and RAM for VMs and Hosts

cfme-cloud_services.gemspec, lib/cfme/cloud_services/data_collector.rb, lib/cfme/cloud_services/payload_builder.rb, spec/data_collector_spec.rb
- inventory is collected to json file
- this json file is packed to `tar.gz`
- `insights-client` is used for sending to cloud
**How to test it**
(if you have ManageIQ::Providers::Vmware::InfraManager provider):
```ruby
target = ManageIQ::Providers::Vmware::InfraManager.first
Cfme::CloudServices::DataCollector.collect(target)
```
=> Add method for inventory upload to insights uploader

lib/cfme/cloud_services/data_collector.rb, spec/data_collector_spec.rb
Allow for the future possibility of having multiple providers per
provider type by using an array for each ems_type.
=> Allow for multiple providers per provider type

lib/cfme/cloud_services/data_collector.rb
Extensions:
```
"ems_extensions": [
{
"id": 1,
"ems_ref": "com.vmware.vim.sms",
"key": "com.vmware.vim.sms",
"company": "VMware Inc.",
"label": "VMware vCenter Storage Monitoring Service",
"summary": "Storage Monitoring and Reporting",
"version": "6.7.0"
}
```
Licenses:
```
"ems_licenses": [
{
"id": 1,
"ems_ref": "00000-00000-00000-00000-00000",
"name": "VMware vCenter Server 6 Standard",
"license_key": "00000-00000-00000-00000-00000",
"license_edition": "vc.standard.instance",
"total_licenses": 6,
"used_licenses": 1
},
```
=> Add ems_extensions and ems_licenses to payload

lib/cfme/cloud_services/data_collector.rb
EmsCluster:
```
{
"id"=>1,
"uid_ems"=>"domain-c109",
"ems_ref"=>"domain-c109",
"ha_enabled"=>false,
"drs_enabled"=>true,
"effective_cpu"=>122271,
"effective_memory"=>387353411584
}
```
Hosts:
```
{
"id"=>3,
"name"=>"dell-r430-21",
"type"=>"ManageIQ::Providers::Vmware::InfraManager::HostEsx",
"hostname"=>"dell-r430-21",
"ipaddress"=>"1.2.3.4",
"power_state"=>"on",
"guid"=>"81ed14c3-968d-4f33-952f-c507b9c721a3",
"uid_ems"=>"dell-r430-21",
"mac_address"=>nil,
"maintenance"=>false,
"vmm_vendor"=>"vmware",
"vmm_version"=>"6.7.0",
"vmm_product"=>"ESXi",
"vmm_buildnumber"=>"8169922",
"archived"=>false,
"cpu_cores_per_socket"=>10,
"cpu_total_cores"=>20,
"ems_cluster_id"=>1
}
```
Storages:
```
{
"id"=>1,
"name"=>"NFS Share",
"location"=>"08e49cea-d9221d10",
"store_type"=>"NFS", …
```
=> Add Hosts, EmsClusters, and Storages to manifest

lib/cfme/cloud_services/manifest_fetcher.rb, spec/inventory_sync_spec.rb
To reduce the number of times the manifest has to be downloaded from
insights we can cache the manifest file for 5 minutes.
=> Cache the manifest file to reduce REST API calls

app/controllers/api/red_hat_cloud_service_providers_controller.rb
We need a version on the manifest, this ensures that we do not think
"version" is a type of provider.
=> Handle a manifest version in the payload

app/controllers/api/red_hat_cloud_service_providers_controller.rb, app/controllers/api/red_hat_cloud_services_controller.rb, app/javascript/packs/red_hat_cloud_services_list.jsx, config/api.yml, spec/requests/red_hat_cloud_service_providers_spec.rb, spec/requests/red_hat_cloud_services_spec.rb
Enhancing the API to support  bulk queueing by leveraging the new API Collection actions and extending the sync action including a new sync_all as well as sync_platform for the "core" (non provider) part of the platform via /api/red_hat_cloud_services
POST /api/red_hat_cloud_service_providers   - action "sync"       with provider_ids specified.
POST /api/red_hat_cloud_service_providers   - action "sync_all"
POST /api/red_hat_cloud_services                   - action "sync_platform"
=> Enhancing API to support sync_all and sync_platform

lib/cfme/cloud_services/data_collector.rb
Added a `data_collected_on` timestamp to the top of the payload so that applications can track the age and deltas from multiple uploads.
=> added data_collected_on to payload

app/controllers/red_hat_cloud_services_controller.rb, lib/cfme/cloud_services/engine.rb
There is an issue when user select Menu Item under `Services` items under `Red Hat Cloud  Services` also get selected. It was caused by using same id `services` for menu items.
https://bugzilla.redhat.com/show_bug.cgi?id=1733489
=> Show Active menu items correctly

config/settings.yml, lib/cfme/cloud_services/manifest_fetcher.rb, spec/manifest_fetcher_spec.rb
When downloading the manifest from insights-ci we need to not verify
ssl.
=> Allow settings to override the verify_ssl param

lib/cfme/cloud_services/data_packager.rb, lib/cfme/cloud_services/inventory_sync.rb
Adds a top-level method to collect and package inventory as well as a
_queue method which returns a task for the API to call.
This is useful if the manifest can't be fetched from the API and when
the payload can't be posted directly to insights via the
insights-client.
=> Add a method to collect and package inventory

lib/cfme/cloud_services/manifest_fetcher.rb, spec/manifest_fetcher_spec.rb
the other benefit is that it will not continue with sending empty inventory to cloud (I guess this is not needed) on errors with obtaining manifest.
@miq-bot assign @agrare
=> Raise error when there is issue on endpoint in ManifestFest

lib/cfme/cloud_services/manifest_fetcher.rb
Use Vmdb::Settings.filter_passwords! to filter out any password
properties from the manifest.
https://github.com/ManageIQ/manageiq/pull/19144
=> Filter out password fields from the manifest

lib/cfme/cloud_services/data_packager.rb
Large files cause `"You tried to feed more data than fits in the file."`
error from Rubygems tar file writer.  The solution is to pass bytesize
instead of length to add_file_simple.
Note: I didn't observe this on a GNU/Linux machine but it was seen on a
Mac with a 10KiB resulting tgz file.  I'm guessing there is a difference
in byte size between int, long, and long long on the different systems.
=> Fix an integer overflow error for large files

lib/cfme/cloud_services/data_packager.rb, lib/cfme/cloud_services/inventory_sync.rb
The file that gets created by Tempfile always has access mode 0600 and
cannot be overridden by the caller.  This isn't always ideal so provide
an option to the caller of modifying the access mode after the file is
created.
=> Allow file permissions to be set by caller

lib/cfme/cloud_services/inventory_sync.rb
This is to send back IP address of the appliance, where the actual payload is stored / saved.
Sample task result when sent over API:
```
{
"href": "http://localhost:3000/api/tasks/350",
"id": "350",
"name": "Collect and package inventory",
"state": "Finished",
"status": "Ok",
"message": "Task completed successfully",
"userid": "admin",
"created_on": "2019-08-22T13:50:05Z",
"updated_on": "2019-08-22T13:50:07Z",
"pct_complete": null,
"context_data": {
"payload_path": "/tmp/cfme_inventory-20190822-30550-1ufxu0p.tar.gz",
"ip_address": "192.168.1.17"
},
"results": null,
"miq_server_id": "3",
"identifier": null,
"started_on": "2019-08-22T13:50:06Z",
"zone": null,
"actions": [
{
"name": "delete",
"method": "post",
"href": "http://localhost:3000/api/tasks/350"
},
{
"name": "delete",
"method": …
```
=> Add ip address to context data

lib/cfme/cloud_services/manifest_fetcher.rb
now:
this error message is displayed here.
but I believe that @PanSpagetka can just display the error message in dialog nicely.
https://bugzilla.redhat.com/show_bug.cgi?id=1740133
@miq-bot assign @agrare
=> Better message when certificates are missing in ManifestFetcher

lib/cfme/cloud_services/data_uploader.rb, spec/data_uploader_spec.rb
According to my testing,`insights_client` sends error output to standard error output on failure but `insights_client` as command has exit code 0 .
https://bugzilla.redhat.com/show_bug.cgi?id=1747178
@miq-bot assign @agrare
=> Log failure(by setting exit_code=1) when insights_client fails with exit_code=0

.travis.yml
Now that master only supports ruby 2.5+ disable testing with ruby 2.4
https://travis-ci.org/RedHatCloudForms/cfme-cloud_services/jobs/605717567
=> Test with ruby 2.5.7 and 2.6.5
